/*
Copyright (c) 2008 Yahoo! Inc.  All rights reserved.  
The copyrights embodied in the content of this file are licensed under the BSD (revised) open source license
*/

/**
 *  Additional vertical space between lines of text.
 *
 *  <p>The default value is 2.</p>
 *  <p>The default value for the ComboBox control is 0.</p>
 */
[Style(name="leading", type="Number", format="Length", inherit="yes")]
