/*
Copyright (c) 2008 Yahoo! Inc.  All rights reserved.  
The copyrights embodied in the content of this file are licensed under the BSD (revised) open source license
*/

/**
 *  Number of pixels between children in the horizontal direction.
 *  The default value depends on the component class;
 *  if not overriden for the class, the default value is 8.
 */
[Style(name="horizontalGap", type="Number", format="Length", inherit="no")]

/**
 *  Number of pixels between children in the vertical direction.
 *  The default value depends on the component class;
 *  if not overriden for the class, the default value is 6.
 */
[Style(name="verticalGap", type="Number", format="Length", inherit="no")]
